# Defines which nodes are used in the system and how to connect to them.
# This element should only be referenced during the constructor's initial
# setup.
# All names must be unique.
# No other nodes are known.
# These names will be used for src and dest addresses for the Message
# The local node's name is included in this list

configuration :
  - name : minglei_nodea
    ip   : 128.237.173.23
    port : 1987
  - name : minglei_nodeb
    ip   : 128.237.173.23
    port : 1988
  - name : yutao_nodea
    ip   : 128.237.208.129
    port : 1989
  - name : logger
    ip   : 128.237.208.129
    port : 1990

sendRules :
  - action : drop 	
    src : bob
    dest : alice
    kind : Ack
    seqNum : 4
  - action : duplicate
    kind : ack
  - action : drop
    kind : xxx

receiveRules :
  - action : drop
    duplicate : true
    
clockType : vector